feat: initial implementation
carlsberg/configuration-fetch-action pull request #1
Opened 2022-06-08 15:39 UTC by jsmvaldivia

New action to fetch AWS appconfig configuration

2022-06-09 13:47 UTC, crqra requested changes
Apart from the comments, don't forget to add at least a `CODEOWNERS` and `LICENSE` files.

The `README.md` file should also mention the license at the bottom.

Apart from that, great job! :shipit:

2022-06-09 13:47 UTC, crqrdotcom commented on README.md
> +- AWS AppConfig Application should exist already
Space between header and list.

2022-06-09 13:47 UTC, crqrdotcom commented on README.md
> +
Space between list items

2022-06-09 13:47 UTC, crqrdotcom commented on README.md
> +
Unnecessary space before header

2022-06-09 13:47 UTC, crqrdotcom commented on README.md
> +
Unnecessary newlines

2022-06-09 13:47 UTC, crqrdotcom commented on README.md
> +Having repo with a previously convened directory structure can be helpfull.
Maybe the phrase could be simplified?

```suggestion
We recommend repositories to have the following directory structure: 
```

2022-06-09 13:47 UTC, crqrdotcom commented on action.yml
> +  appName:
Prefer "kebab-case" for input names (following the official GitHub Actions standards).

2022-06-09 13:47 UTC, crqrdotcom commented on action.yml
> +author: "Juan Valdivia"
Add branding information so it's ready to be published if we decide to do so.

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding

2022-06-09 13:47 UTC, crqrdotcom commented on main.go
> +	action.SetOutput("config", config)
Output specified here but wasn't specified neither in the `action.yml` nor the `README.md` files.

2022-06-09 13:47 UTC, crqrdotcom commented on aws/aws.go
> +func awsSdkConfig(region string) (aws.Config, error) {
Consider adding a `context.Context` argument here and pass the same context used for the other AWS functions.

2022-06-09 13:47 UTC, crqrdotcom commented on aws/aws.go
> +func GetConfig(appName, profileName, env, region string) (string, error) {
Consider adding a `context.Context` here that can be passed by the calling code and re-used in every AWS function (better if we ever decide to do something we the context we can do it in the main file instead of having to update multiple places).

2022-06-09 13:54 UTC, jsmvaldivia commented on action.yml
> +  appName:
updating it, makes sense

2022-06-09 14:04 UTC, jsmvaldivia commented on action.yml
> +author: "Juan Valdivia"
@crqra there is another action quite similar that where we also need to handle this, if it seems fine, I'll handle it later in a new PR

2022-06-09 14:04 UTC, jsmvaldivia commented on main.go
> +	action.SetOutput("config", config)
well spotted! thanks

2022-06-09 14:22 UTC, jsmvaldivia commented on README.md
> +- AWS AppConfig Application should exist already
Removed space

2022-06-09 14:26 UTC, jsmvaldivia commented on README.md
> +
removed

2022-06-09 14:29 UTC, jsmvaldivia commented on README.md
> +
I removed just 1 line, like the extra space to read the MD

2022-06-09 14:29 UTC, jsmvaldivia commented on README.md
> +
removed

2022-06-09 14:29 UTC, jsmvaldivia commented on action.yml
> +  appName:
agreed and changed

2022-06-09 14:42 UTC, jsmvaldivia commented on aws/aws.go
> +func GetConfig(appName, profileName, env, region string) (string, error) {
sounds reasonable

2022-06-09 14:42 UTC, jsmvaldivia commented on aws/aws.go
> +func awsSdkConfig(region string) (aws.Config, error) {
sounds reasonable

2022-06-14 15:15 UTC, crqra approved these changes
LGTM! 👍🏼

2022-06-14 15:15 UTC, crqra commented on README.md
> +
That was the only one to be removed 😋

2022-06-14 17:13 UTC, merged